# Generated by Django 4.1.1 on 2023-06-23 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BookCover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='BookCover'),
            preserve_default=False,
        ),
    ]
